# Experiment No. 1

### Roll No.: 18BIC026 Joy Mehta

Date: 23/07/2020

## Aim: 
#### Variables, Numpy Arrays, expressions and functions in python. 

## Objectives:

>To implement operations with variables, Numpy Arrays, expressions and functions in python.

### Pre-Lab Exercise:
1. Learn about variables, Numpy Arrays, expressions and functions.

### Reference Book:
1. Downey, Allen. Think Python. “O’Reilly Media, Inc.", 2012.

## Programming Exercise:

In [2]:
#importing random library
import random as r

In [4]:
#print random no. in range 1-1000 
r.randint(1,1000)

449

In [5]:
#print 10 random numbers
for i in range(10):
  print(r.randint(1, 100))

5
68
60
90
48
68
39
47
60
61


In [7]:
#print 200 random numbers horizintally
for i in range(20):
  print(r.randint(1, 100), end=",")

21,6,97,100,2,84,57,5,49,18,71,19,29,94,76,57,24,73,65,11,

In [9]:
#generate 10 random numbers without repeatation
r.sample(range(1, 100), 10)

[27, 77, 6, 71, 88, 81, 69, 14, 98, 5]

In [10]:
#generate random number with specific interval
for i in range(10):
  print(r.randrange(1, 100, 3), end=",")

88,22,91,40,70,97,94,46,91,13,

In [13]:
#random float numbers
r.uniform(-3, 3)

-0.16774893613410713

In [15]:
#generate random float number with 5 decimal point
format(r.uniform(10, 20), '.5f')

'19.92280'

In [17]:
#generate 10 random float numbers
for i in range(10):
  print(format(r.uniform(1,10), '.2f'), end="|")

2.04|6.97|3.56|5.90|7.67|4.15|5.45|3.35|4.89|9.44|

In [19]:
#import numpy
import numpy as np

In [20]:
#generate random number array
np.random.randint(1, 100, 5)

array([31, 38, 75, 54, 13])

In [22]:
#generate 20 random float number array
np.random.ranf(20)

array([0.58597645, 0.32252778, 0.43238475, 0.43755763, 0.18583346,
       0.61113552, 0.21265767, 0.33738988, 0.7406151 , 0.19533521,
       0.62342472, 0.0040537 , 0.47130723, 0.86178793, 0.55493842,
       0.5291374 , 0.90252614, 0.58615985, 0.03904643, 0.57960922])

In [25]:
#generate 15 random float numbers with 2 decimal point place bw 0 and 1
np.round(np.random.ranf(15), decimals=2)

array([0.84, 0.85, 0.22, 0.81, 0.85, 0.98, 0.48, 0.97, 0.59, 0.89, 0.6 ,
       0.35, 0.81, 0.08, 0.2 ])

In [31]:
#generate 10 random float numbers in range 1-5
np.random.uniform(1, 5, 10)

array([1.76148986, 3.28596124, 2.46025052, 4.96868493, 3.65617105,
       1.64408871, 1.09526566, 2.61392542, 2.46964369, 4.07677496])

In [32]:
#roundoff randomly generated float numbers to 2 decimals
np.round(np.random.uniform(1, 5, 10), decimals=2)

array([2.16, 4.59, 2.62, 1.11, 2.44, 1.36, 4.55, 3.14, 4.09, 1.89])

In [34]:
#generate randmom numbers and store them in a matrix
np.random.sample((5,4))

array([[0.26770926, 0.42691096, 0.17162341, 0.46491927],
       [0.96499359, 0.89763565, 0.68231144, 0.88870403],
       [0.14415003, 0.01708817, 0.55145395, 0.5514044 ],
       [0.81313963, 0.77618836, 0.83143911, 0.27074521],
       [0.48894886, 0.57266397, 0.16709137, 0.12376432]])

In [37]:
#conventional python list
l1 = [1,2,3]
l2 = [5,3,2]
l1 + l2
#this concatenate both lists elements and outputs a list

[1, 2, 3, 5, 3, 2]

In [38]:
#np.array individually adds the elements to the corresponding element in the next list
l1 = np.array([2,3,5,2])
l2 = np.array([1, 2, 2 ,22])
l1 + l2

array([ 3,  5,  7, 24])

In [40]:
#generate an list of 30 random numbers in range of 1-100
arr1 = np.array(r.sample(range(1, 100), 50))
print(arr1)

[26 42 83 19 81 28 95 50 64 94 99 93 15 58 96 91 79 45 74 86  4 67 88 52
  5 78 70 98  2 60 84 51 25 54 48  8 23 31 85 65 73 34 36 13 63 82 41 37
 69 32]


In [42]:
#reshape arr1 into 5x10 array
arr1.reshape((5, 10))

array([[26, 42, 83, 19, 81, 28, 95, 50, 64, 94],
       [99, 93, 15, 58, 96, 91, 79, 45, 74, 86],
       [ 4, 67, 88, 52,  5, 78, 70, 98,  2, 60],
       [84, 51, 25, 54, 48,  8, 23, 31, 85, 65],
       [73, 34, 36, 13, 63, 82, 41, 37, 69, 32]])

In [48]:
#create a 5x5 array
dataset = np.random.sample((5,5))
print(dataset)

[[0.51652952 0.82585391 0.31313959 0.49436973 0.89561267]
 [0.79741258 0.23329627 0.24103558 0.34823734 0.98165232]
 [0.11925573 0.6366967  0.78765822 0.33966891 0.91436038]
 [0.34615738 0.39850297 0.31621928 0.62330216 0.58745738]
 [0.78699308 0.28322331 0.95606575 0.02723569 0.6916074 ]]


In [49]:
#access various elements of the array
dataset[:,0] #First column

array([0.51652952, 0.79741258, 0.11925573, 0.34615738, 0.78699308])

In [51]:
dataset[0] #First Column

array([0.51652952, 0.82585391, 0.31313959, 0.49436973, 0.89561267])

In [52]:
dataset[2][3] #Access 4th element from 3rd row

0.33966891194587756

In [53]:
dataset[-3:] #access last 3 rows

array([[0.11925573, 0.6366967 , 0.78765822, 0.33966891, 0.91436038],
       [0.34615738, 0.39850297, 0.31621928, 0.62330216, 0.58745738],
       [0.78699308, 0.28322331, 0.95606575, 0.02723569, 0.6916074 ]])

In [57]:
dataset[:,-3] #print 3rd last column of dataset

array([0.31313959, 0.24103558, 0.78765822, 0.31621928, 0.95606575])

In [59]:
dataset[:, -3:] #print last 3 columns of datase

array([[0.31313959, 0.49436973, 0.89561267],
       [0.24103558, 0.34823734, 0.98165232],
       [0.78765822, 0.33966891, 0.91436038],
       [0.31621928, 0.62330216, 0.58745738],
       [0.95606575, 0.02723569, 0.6916074 ]])

## Conclusion

* In this lab we were introduced to python programming and librarie like random and numpy.

* We leanred functions of these libraries, like generating random numbers, generating random numbers between different range, generating random numbers with intervals, using arrays with numpy, reshaping an array, generating a matrix with random numbers and accessing different elements of a matrix generated.